spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: YOUR_CLIENT_ID
            client-secret: YOUR_CLIENT_SECRET
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://lhost:8080/api/v1/budget
